name: Protect Main Branch

on:
  push:
    branches:
      - main

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce branch protection
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          curl -X PUT -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github.luke-cage-preview+json" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/branches/main/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": ["validate"]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": null
          }'
